import { colorKeys } from "../../colors";
import { INFINITE_TIME } from "../../consts";
import { StageDefinition } from "../../types/GameDifficulty";
import { ThirteenElements } from "../../types/ThirteenElements";

export const stageDefinitions: ThirteenElements<StageDefinition> = [
  {
    legionName: "First Legion of Prison Guards",
    stageName: "Prison Sewers",
    skyColor: colorKeys.s1,
    groundColor: colorKeys.g1,
    enemyWalkingSpeedMultiplier: 0.2,
    enemyAttackTimeInMs: 800,
    enemyAttackCooldownInMs: 500,
    enemyMaxHp: 100,
    enemyDmg: 60,
    spawnFrequencyRangeInMs: [2000, 3500],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [4000, 8000],
    rockDmg: 15,
    rockFallingSpeed: 0.15,
  },
  {
    legionName: "Second Legion of Demented Lamplighters",
    stageName: "Unlit Lanterns District",
    skyColor: colorKeys.s2,
    groundColor: colorKeys.g2,
    enemyWalkingSpeedMultiplier: 0.5,
    enemyAttackTimeInMs: 100,
    enemyAttackCooldownInMs: 100,
    enemyMaxHp: 55,
    enemyDmg: 10,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Third Legion of River ...",
    stageName: "Riverside",
    skyColor: colorKeys.s3,
    groundColor: colorKeys.g3,
    enemyWalkingSpeedMultiplier: 0.18,
    enemyAttackTimeInMs: 800,
    enemyAttackCooldownInMs: 500,
    enemyMaxHp: 150,
    enemyDmg: 80,
    spawnFrequencyRangeInMs: [2000, 3000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Fourth Legion of ",
    stageName: "Mystical Forest",
    skyColor: colorKeys.s4,
    groundColor: colorKeys.g4,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Fifth Legion of ",
    stageName: "Contaminated Plains",
    skyColor: colorKeys.s5,
    groundColor: colorKeys.g5,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Sixth Legion of Possessed Monks",
    stageName: "Forsaken Temple",
    skyColor: colorKeys.s6,
    groundColor: colorKeys.g6,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Seventh Legion of Ashen Nomads",
    stageName: "Desert of Ashes",
    skyColor: colorKeys.s7,
    groundColor: colorKeys.g7,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Eighth Legion of Exiled Prisoners",
    stageName: "Growing Wastelands of Frost",
    skyColor: colorKeys.s8,
    groundColor: colorKeys.g8,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Ninth Legion of Fallen Angels",
    stageName: "Heavenly Peaks",
    skyColor: colorKeys.s9,
    groundColor: colorKeys.g9,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Tenth Legion of Blinded Wanderers",
    stageName: "Valley of the Dead",
    skyColor: colorKeys.s10,
    groundColor: colorKeys.g10,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Eleventh Legion of Restless Spirits",
    stageName: "Forgotten Graveyard",
    skyColor: colorKeys.s11,
    groundColor: colorKeys.g11,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Twelfth Legion of Bloodthirsty Berserkers",
    stageName: "Desolated Battlegrounds",
    skyColor: colorKeys.s12,
    groundColor: colorKeys.g12,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
  {
    legionName: "Thirteenth Legion of Relentless ...",
    stageName: "Haven of Lost Hope",
    skyColor: colorKeys.s13,
    groundColor: colorKeys.g13,
    enemyWalkingSpeedMultiplier: 0.7,
    enemyAttackTimeInMs: 200,
    enemyAttackCooldownInMs: 200,
    enemyMaxHp: 75,
    enemyDmg: 20,
    spawnFrequencyRangeInMs: [1000, 5000],
    spawnMinDistanceFromPlayer: 250,
    terrain: [
      {
        x: 200,
        y: 425,
        w: 200,
        h: 25,
      },
      {
        x: 800,
        y: 425,
        w: 200,
        h: 25,
      },
    ],
    rockSpawnFrequencyInMs: [INFINITE_TIME, INFINITE_TIME],
    rockDmg: 0,
    rockFallingSpeed: 0,
  },
];
